[project]
name = "apachebeaminferenceml"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "apache-beam[gcp]>=2.66.0",
    "google-cloud-bigquery>=3.34.0",
    "google-cloud-storage>=2.19.0",
]
